training_pipeline_config:
  pipeline_name: premium
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://github.com/Vish2427/Data_Set/raw/main/Insurance.tgz
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test